-- PostgreSQL/Supabase schema for Vite&Gourmande

DROP TABLE IF EXISTS avis;
DROP TABLE IF EXISTS commande_suivis;
DROP TABLE IF EXISTS commandes;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS plats;
DROP TABLE IF EXISTS utilisateurs;
DROP TABLE IF EXISTS menus;

CREATE TABLE IF NOT EXISTS menus (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL,
    description TEXT,
    nb_personnes_min INTEGER NOT NULL DEFAULT 1,
    prix_minimum NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_menus_actif ON menus(actif);

CREATE TABLE IF NOT EXISTS plats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_id BIGINT NOT NULL,
    nom VARCHAR(160) NOT NULL,
    type VARCHAR(20) NOT NULL CHECK (type IN ('entree', 'plat', 'dessert', 'boisson')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_plats_menu_id ON plats(menu_id);
CREATE INDEX IF NOT EXISTS idx_plats_type ON plats(type);

CREATE TABLE IF NOT EXISTS utilisateurs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL,
    prenom VARCHAR(120) NOT NULL,
    gsm VARCHAR(30) NOT NULL,
    email VARCHAR(190) NOT NULL UNIQUE,
    adresse_postale VARCHAR(255) NOT NULL,
    mot_de_passe VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL DEFAULT 'utilisateur' CHECK (role IN ('utilisateur', 'employe', 'administrateur')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS commandes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    utilisateur_id BIGINT NOT NULL,
    menu_id BIGINT NOT NULL,
    nom_client VARCHAR(120) NOT NULL,
    prenom_client VARCHAR(120) NOT NULL,
    email_client VARCHAR(190) NOT NULL,
    gsm_client VARCHAR(30) NOT NULL,
    adresse_client VARCHAR(255) NOT NULL,
    date_prestation DATE NOT NULL,
    heure_livraison TIME NOT NULL,
    lieu_livraison VARCHAR(255) NOT NULL,
    ville_livraison VARCHAR(120) NOT NULL,
    distance_km NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    nb_personnes INTEGER NOT NULL,
    prix_menu NUMERIC(10,2) NOT NULL,
    remise NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    frais_livraison NUMERIC(10,2) NOT NULL DEFAULT 0.00,
    prix_total NUMERIC(10,2) NOT NULL,
    statut VARCHAR(30) NOT NULL DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'accepte', 'en_preparation', 'en_cours_de_livraison', 'livre', 'terminee', 'annulee')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_commandes_utilisateur ON commandes(utilisateur_id);
CREATE INDEX IF NOT EXISTS idx_commandes_menu ON commandes(menu_id);
CREATE INDEX IF NOT EXISTS idx_commandes_statut ON commandes(statut);

CREATE TABLE IF NOT EXISTS commande_suivis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id BIGINT NOT NULL,
    statut VARCHAR(60) NOT NULL,
    commentaire VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_suivis_commande_id ON commande_suivis(commande_id);
CREATE INDEX IF NOT EXISTS idx_suivis_created_at ON commande_suivis(created_at);

CREATE TABLE IF NOT EXISTS avis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id BIGINT NOT NULL,
    utilisateur_id BIGINT NOT NULL,
    note SMALLINT NOT NULL,
    commentaire TEXT NOT NULL,
    statut VARCHAR(20) NOT NULL DEFAULT 'en_attente' CHECK (statut IN ('en_attente', 'valide', 'refuse')),
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_avis_commande UNIQUE (commande_id)
);
CREATE INDEX IF NOT EXISTS idx_avis_statut ON avis(statut);
CREATE INDEX IF NOT EXISTS idx_avis_utilisateur ON avis(utilisateur_id);

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(120) NOT NULL,
    email VARCHAR(190) NOT NULL,
    titre VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(email);
CREATE INDEX IF NOT EXISTS idx_contacts_created_at ON contacts(created_at);

INSERT INTO menus (id, nom, description, nb_personnes_min, prix_minimum, actif)
VALUES
    (1, 'Menu de Noel', 'Menu festif pour les repas de Noel', 6, 180.00, TRUE),
    (2, 'Menu de Paques', 'Menu special pour Paques', 6, 170.00, TRUE),
    (3, 'Menu Evenement', 'Menu pour les evenements prives et pros', 10, 320.00, TRUE),
    (4, 'Menu Classique', 'Menu classique disponible toute l annee', 4, 95.00, TRUE)
ON CONFLICT (id) DO UPDATE SET
    nom = EXCLUDED.nom,
    description = EXCLUDED.description,
    nb_personnes_min = EXCLUDED.nb_personnes_min,
    prix_minimum = EXCLUDED.prix_minimum,
    actif = EXCLUDED.actif;

INSERT INTO plats (id, menu_id, nom, type)
VALUES
    (1, 1, 'Foie gras maison', 'entree'),
    (2, 1, 'Veloute de chataignes', 'entree'),
    (3, 1, 'Chapon farci aux marrons', 'plat'),
    (4, 1, 'Gratin dauphinois', 'plat'),
    (5, 1, 'Buche de Noel chocolat', 'dessert'),
    (6, 2, 'Asperges sauce mousseline', 'entree'),
    (7, 2, 'Oeuf cocotte truffe', 'entree'),
    (8, 2, 'Gigot d agneau aux herbes', 'plat'),
    (9, 2, 'Gratin de pommes de terre', 'plat'),
    (10, 2, 'Charlotte aux fraises', 'dessert'),
    (11, 3, 'Verrines de saumon', 'entree'),
    (12, 3, 'Planches de charcuterie', 'entree'),
    (13, 3, 'Buffet chaud au choix', 'plat'),
    (14, 3, 'Riz pilaf et legumes', 'plat'),
    (15, 3, 'Assortiment de desserts', 'dessert'),
    (16, 4, 'Salade nicoise', 'entree'),
    (17, 4, 'Soupe a l oignon gratinee', 'entree'),
    (18, 4, 'Boeuf bourguignon', 'plat'),
    (19, 4, 'Pommes de terre vapeur', 'plat'),
    (20, 4, 'Tarte Tatin maison', 'dessert')
ON CONFLICT (id) DO UPDATE SET
    nom = EXCLUDED.nom,
    type = EXCLUDED.type;

SELECT setval('menus_id_seq', COALESCE((SELECT MAX(id) FROM menus), 1), TRUE);
SELECT setval('plats_id_seq', COALESCE((SELECT MAX(id) FROM plats), 1), TRUE);
